feat: implement dev mode
ostis-ai/react-sc-web pull request #12
Opened 2024-03-06 11:15 UTC by gotovvar

2024-04-11 07:35 UTC, MksmOrlov requested changes
How to launch it?
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/a104a28b-a517-451a-87f0-b45d064d81e3)
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/23914984-e555-4d75-ab29-848bbf32596c)

2024-04-11 11:22 UTC, MksmOrlov requested changes
окей, вроде запустил, но все равно ребейз на меин надо сделать.
1. При первом запуске появляется окошко с троеточием у поиска, хотя я туда не наводился
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/b504fccd-03c9-4245-8328-1ad7282fbc2f)
2. На что бы я ни наводился, я вижу либо ..., либо тот же самый текст, на который навёлся. Кажется, оно должно работать по-другому

2024-04-11 11:22 UTC, MksmOrlov commented on src/components/DecompositionPanel/DecompositionPanel.tsx
это ж копипаст из библиотеки ostis-ui-lib, не вижу тут ничего нового

2024-04-11 11:22 UTC, MksmOrlov commented on src/components/DecompositionPanel/components/EditTextarea/EditTextarea.tsx
тоже копипаст

2024-04-11 11:22 UTC, MksmOrlov commented on src/components/ToolTip/ToolTip.tsx
> +    );
Как я могу проверить это? Нужно, чтобы вы добавили конструкцию в БЗ для проверки

2024-04-11 15:29 UTC, gotovvar commented on src/components/DecompositionPanel/DecompositionPanel.tsx
@MksmOrlov Тут и не должно быть ничего нового. Потому что мне надо было обернуть в тултип компонент `ScLangText` внутри компонента `NavigationItem`. А отдельно я его достать не мог поэтому пришлось копипастить весь компонент из ostis-ui-lib.

2024-04-11 15:54 UTC, gotovvar commented on src/components/Accordion/Accordion.tsx
> +    header === 'История' || header === 'History' ? 'ui_history_panel' : 'ui_section_panel';
@MksmOrlov Я не очень понимаю как без захардкоженых адресов мне понимать какой адрес к чему относится

2024-04-12 10:31 UTC, gotovvar commented
@MksmOrlov Сделал подтянул изменения с мейна [вот тут](https://github.com/ostis-ai/react-sc-web/commit/31cf5990b243206778e4038896c5eb04820f4c9f)

2024-04-14 08:35 UTC, MksmOrlov commented on src/components/DecompositionPanel/DecompositionPanel.tsx
ладно :)

2024-04-14 08:38 UTC, MksmOrlov commented on src/components/ToolTip/ToolTip.tsx
> +    );
жду

2024-04-14 08:40 UTC, MksmOrlov commented on src/components/Accordion/Accordion.tsx
> +    header === 'История' || header === 'History' ? 'ui_history_panel' : 'ui_section_panel';
@MikhailSadovsky что думаешь с этим можно делать?

2024-04-15 11:50 UTC, MksmOrlov requested changes
Базу знаний подобрал, но все ещё не вижу ничего, что даёт dev-mode. Везде троеточия

2024-04-15 12:44 UTC, MksmOrlov requested changes

2024-04-15 12:44 UTC, MksmOrlov commented on src/components/ScnBase/mock/constants.ts
этачё

2024-04-15 12:44 UTC, MksmOrlov commented on src/components/ToolTip/Tooltip.module.scss
> +    z-index: 9999;
не надо так много, найдите минимальное корректное значение

2024-04-15 14:44 UTC, gotovvar commented on src/components/ScnBase/mock/constants.ts
@MksmOrlov С `ostis-ui-lib` взят компонент так что не знаю

2024-04-16 12:45 UTC, MksmOrlov approved these changes

2024-04-17 09:39 UTC, closed without merging