feat: implement auth page and dev mode
ostis-ai/react-sc-web pull request #13
Opened 2024-03-13 13:11 UTC by kitanoyoru

2024-04-04 13:33 UTC, kitanoyoru commented
@MikhailSadovsky @MksmOrlov Агента коммитить нужно сюда [ostis-metasystem](https://github.com/ostis-ai/ostis-metasystem)?

2024-04-09 08:46 UTC, MksmOrlov commented
> @MikhailSadovsky @MksmOrlov Агента коммитить нужно сюда [ostis-metasystem](https://github.com/ostis-ai/ostis-metasystem)?

да. А что за агент?

2024-04-09 08:58 UTC, kitanoyoru commented on src/pages/Auth/Auth.tsx
> +          </div>
@MksmOrlov Она была на дизайне

2024-04-09 08:59 UTC, kitanoyoru commented
> > @MikhailSadovsky @MksmOrlov Агента коммитить нужно сюда [ostis-metasystem](https://github.com/ostis-ai/ostis-metasystem)?
> 
> да. А что за агент?

Агент авторизации

2024-04-09 09:13 UTC, kitanoyoru commented on src/pages/Auth/Auth.tsx
> +          </div>
@MksmOrlov Пофиксил стили

2024-04-09 10:28 UTC, MksmOrlov commented on src/pages/Auth/Auth.tsx
> +          </div>
@MikhailSadovsky пусть будет кнопка забыли пароль?

2024-04-11 07:54 UTC, MksmOrlov requested changes
How to launch it? What repos and branches do you use? I tried metasystem on `feature/authorise-agent`
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/6bd01518-4255-4102-8013-7675d4f93c5b)
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/a135ee4e-7eb0-41e4-9d4b-1baa4a985ec9)

2024-04-11 12:22 UTC, MksmOrlov requested changes
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/ee26fbf8-c003-457e-bec9-970963f09d6c)
При нажатии на глазик курсор почему-то убегает в начало строки

2024-04-11 12:22 UTC, MksmOrlov commented on .gitignore
> +.env
не надо

2024-04-11 12:22 UTC, MksmOrlov commented on README.md
форматить все файлы тоже не надо

2024-04-11 12:22 UTC, MksmOrlov commented on README.md
оставь только свои изменения по логике

2024-04-11 12:22 UTC, MksmOrlov commented on src/pages/Auth/Auth.tsx
> +          <Button className={styles.loginFormSubmit}>Submit</Button>
На русском языке кнопка sub,it по-английски написана. Это неправильно, надо по-русски

2024-04-15 13:35 UTC, MikhailSadovsky commented on src/pages/Auth/Auth.tsx
> +          </div>
пусть будет

2024-04-15 17:17 UTC, MksmOrlov requested changes
не исправлены замечания выше, агент не запускается

2024-04-16 11:09 UTC, kitanoyoru commented on .gitignore
> +.env
@MksmOrlov Убрал

2024-04-16 11:12 UTC, kitanoyoru commented
@MksmOrlov Поправил все что можно выше, кроме скрытия пароля в инпут баре. Компонент брал из `ostis-ui-lib`, так что лучше завести туда issue и чтобы человек, который это писал, поправил его

Ошибка в том, что при клике на глазик, инпут бар берется в фокус из-за этого и появляется курсор

2024-04-16 12:20 UTC, MksmOrlov requested changes
опять добавили рефакторинг всего проекта. Убрать.
Не входит в метасистему
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/a5ab075e-2f33-44cf-a088-1f0ad88caf29)

2024-04-16 12:48 UTC, kitanoyoru commented
@MksmOrlov Символов пробела точно нет в инпут барах?

2024-04-16 18:18 UTC, MksmOrlov requested changes
Не авторизовывает
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/e52ec635-e1ad-43fa-99ca-878c21197d73)

Пароль и логин ввел точь-в-точь как в гвфке

2024-04-17 06:02 UTC, kitanoyoru commented
@MksmOrlov Дабл клик по кнопке сделайте, скорее всего агент криво написан (точно не фронта, потому что при первом я отсылаю те же данные, что и при втором). При первом клике

<img width="1174" alt="Screenshot 2024-04-17 at 09 01 33" src="https://github.com/ostis-ai/react-sc-web/assets/90549065/11f577f6-4dbe-4188-b1fc-367de9695207">

При втором все ок

2024-04-17 09:56 UTC, merged