Feat/add library page
ostis-ai/react-sc-web pull request #18
Opened 2024-04-08 14:09 UTC by Daer0n

2024-04-09 08:42 UTC, MksmOrlov requested changes
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/fa91a0c3-80b2-4551-bfa4-06daafee8943)

2024-04-09 11:55 UTC, AlexeyTerleev commented
Did you create .env?

2024-04-11 07:43 UTC, MksmOrlov requested changes
what branches do you use to launch it?
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/82ebc675-ccca-4ba2-a28e-b90c5e2a6212)

2024-04-11 12:16 UTC, MksmOrlov requested changes
При старте должен подсвечиваться одна из иконок страницы слева
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/976da690-c935-43fd-af57-39bb856c77e3)
При открытии страницы библиотеки агент поиска вызывается бесконечное количество раз (это видно в логах сервера) 
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/ffafa470-fbcd-44b6-bad4-bcd90e377668)

2024-04-11 12:16 UTC, MksmOrlov commented on src/api/requests/getSpecification.ts
> +    }
здесь напрашивается break, иначе лишние поиски будут

2024-04-11 12:16 UTC, MksmOrlov commented on src/api/sc/install/install.ts
Тоже для вызова агента нужно использовать Action из src/api/sc/actions

2024-04-11 17:30 UTC, AlexeyTerleev commented on src/pages/Library/index.ts
> +export const Library = lazy(() => import(/* webpackChunkName: "liberary" */ './Library'));
https://webpack.js.org/api/module-methods/

2024-04-14 08:28 UTC, MksmOrlov requested changes
что-то поехало
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/d744f1f8-e7e2-475b-86a4-6ed8bd5b1bd7)

2024-04-15 06:55 UTC, MksmOrlov requested changes
При повторном открытии, обновлении страницы, иконка активной библиотеки остаётся, надо бы возвращать то, что реально показывается
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/1f6dc85a-ea73-4192-821c-c6bbc2729e62)

Не закрывается выпадашка фильтра при нажатии на компонент или другую область
![image](https://github.com/ostis-ai/react-sc-web/assets/36566977/ada56ce6-2c45-4f89-b861-e3b816af1ebd)

Иконки переключения режима scn/scg на странице библиотеки надо бы убрать

2024-04-15 13:29 UTC, MikhailSadovsky commented
Сделать курсор-руку при:
- Наведении на любую из карточек, чтобы было понятно, что они кликабельны
- При наведении на крестик внутри карточки
- При наведении на строку (текст и чек-бокс) внутри фильтра

2024-04-15 20:50 UTC, MikhailSadovsky approved these changes

2024-04-16 12:28 UTC, MksmOrlov approved these changes

2024-04-17 09:38 UTC, merged